
import os
from collections import Counter

def length_greater_than(word, length):
	if len(word.strip().split(' ')) > length:
		return True
	else:
		return False

def integrate(input_dir='../data/raw/', output_fn='../data/data.csv'):
	'''
	integrate data from all files generated by reddit_praw.py 
	'''
	ids = set()
	files = [f for f in os.listdir(input_dir) if f.endswith('csv')]
	label_counter = Counter()

	outfile = open(output_fn, 'w', encoding='utf-8')
	for file in files:
		with open(input_dir + file, 'r', encoding='utf-8') as f:
			print(input_dir + file)
			for line in f.readlines():
				# print(line)
				data = line.split('\t')
				# print(data)
				id, title, label = data[0], data[1], data[2]
				if id not in ids and length_greater_than(title, 3) :
					ids.add(id)
					outfile.write(title + '\t' + label)
					label_counter[label] += 1
			# print(f.readlines())
			
	outfile.close()
	return label_counter

def print_counter(label_counter):
	for key in label_counter:
		print('{} {}'.format(key, label_counter[key]))

if __name__ == '__main__':
	label_counter = integrate()
	print_counter(label_counter)